exports.seed = async function (knex) {
  await knex("shipping_fee_configs").del();

  await knex("shipping_fee_configs").insert([
    // ── INTERNATIONAL: weight_rate ──
    {
      name: "KR-VN under 3kg",
      shipping_type: "international",
      pricing_mode: "weight_rate",
      carrier: "system",
      min_weight_grams: 0,
      max_weight_grams: 3000,
      rate_per_kg: 152000,
    },
    {
      name: "KR-VN 3kg-10kg",
      shipping_type: "international",
      pricing_mode: "weight_rate",
      carrier: "system",
      min_weight_grams: 3001,
      max_weight_grams: 10000,
      rate_per_kg: 142500,
    },
    {
      name: "KR-VN 10kg-30kg",
      shipping_type: "international",
      pricing_mode: "weight_rate",
      carrier: "system",
      min_weight_grams: 10001,
      max_weight_grams: 30000,
      rate_per_kg: 133000,
    },
    {
      name: "KR-VN above 30kg",
      shipping_type: "international",
      pricing_mode: "weight_rate",
      carrier: "system",
      min_weight_grams: 30001,
      max_weight_grams: null,
      rate_per_kg: 114000,
    },

    // ── LOCAL: base_step ──
    {
      name: "Local Noi Vung",
      shipping_type: "local",
      pricing_mode: "base_step",
      carrier: "system",
      region: "noi_vung",
      base_fee: 29000,
      step_weight_grams: 500,
      step_fee: 2500,
      free_shipping_threshold: 500000,
    },
    {
      name: "Local Noi Vung Tinh",
      shipping_type: "local",
      pricing_mode: "base_step",
      carrier: "system",
      region: "noi_vung_tinh",
      base_fee: 34000,
      step_weight_grams: 500,
      step_fee: 2500,
      free_shipping_threshold: 500000,
    },
    {
      name: "Local Lien Vung",
      shipping_type: "local",
      pricing_mode: "base_step",
      carrier: "system",
      region: "lien_vung",
      base_fee: 39000,
      step_weight_grams: 500,
      step_fee: 5000,
      free_shipping_threshold: 700000,
    },
    {
      name: "Local Lien Tinh",
      shipping_type: "local",
      pricing_mode: "base_step",
      carrier: "system",
      region: "lien_tinh",
      base_fee: 36000,
      step_weight_grams: 500,
      step_fee: 5000,
      free_shipping_threshold: 700000,
    },
    {
      name: "Local Lien Vung DB",
      shipping_type: "local",
      pricing_mode: "base_step",
      carrier: "system",
      region: "lien_vung_dac_biet",
      base_fee: 39000,
      step_weight_grams: 500,
      step_fee: 5000,
      free_shipping_threshold: 1000000,
    },
  ]);
};